version: '3.8'
services:
  app:
    image: esatto_task
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev  
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    command: npm run dev